---
title: "Research"
toc: false
---

### *ETF mispricing and APs' Inventory (joint work with Andrei Kirilenko, Oliver Linton, and Wladimir Kraus) (JMP, available upon request)*
Authorized Participants (APs), primarily market makers, possess the right to create and redeem Exchange Traded Funds (ETF) shares based on market demand. The important role they play in facilitating liquidity provision and eliminating ETF mispricing makes their behavior crucial to the well-functioning of the ETF market. Using a novel regulatory dataset that covers the primary and secondary market transactions of 128 ETFs from 2018 to 2022, we identify a connection between mispricing (the difference between ETF prices and the Net Asset Value (NAV) of their underlying baskets) and AP’s inventory. We formulate a dynamic model that explains ETF mispricing with AP’s inventory management skills and market demand. Empirical findings are consistent with our model predictions in that the proposed factors are useful for explaining the observed mispricing on top of other common macro and fundamental factors in the ETFs and underlying markets. Our model is helpful for understanding the incentive structure of AP's market making and arbitraging, as well as the mechanisms behind the significant mispricing observed in March 2020 across various ETF classes.

### *High-dimensional Covariance Matrix Estimation: Shrinkage Using a Diagonal Target [[PDF]](Covariance_Matrix_Estimation_with_a_diagonal_target (5).pdf) (joint work with Sakai Ando) (The IMF Working Paper version is available [here](https://www.imf.org/en/Publications/WP/Issues/2023/12/08/High-Dimensional-Covariance-Matrix-Estimation-Shrinkage-Toward-a-Diagonal-Target-542025).)*
This paper proposes a novel shrinkage estimator for high-dimensional covariance matrices by extending the Oracle Approximating Shrinkage (OAS) to target the diagonal elements of the sample covariance matrix. When the diagonal elements of the true covariance matrix exhibit substantial variation, our method reduces the Mean Squared Error, compared with OAS, which targets an average variance. The degree of improvement is higher when the true covariance matrix is sparser. Our method also outperforms other estimators based on a diagonal target under the normality assumption. We further propose an extended estimator that makes use of two targets: the average variance target and the diagonal target. This more flexible estimator improves upon the single-target estimators in all the scenarios discussed. The proposed estimators are applied to the problem of UK inflation forecast reconciliation and minimum variance portfolio selection to compare their performance with other benchmark methods.

### *GMM estimation of dynamic panel data models with invalid moment conditions—the sparse group lasso approach [[PDF]](CovidProject_DPDInvadliMoments (5).pdf)*
This paper primarily focuses on the GMM estimation of dynamic panel data models, where many moment conditions have been proposed under various assumptions. These moment conditions grow quadratically with the number of time periods \(T\), making it difficult for researchers to determine which assumptions are satisfied in practice. Additionally, the presence of too many moment conditions can adversely affect the performance of the estimator. To address this, we explore the use of the sparse group lasso method for selecting valid moment conditions from a pool of potentially invalid ones. This paper reviews and compares existing methods with the sparse group lasso approach and provides simulation results to evaluate their performance. The application of the sparse group lasso method in dynamic panel data estimation demonstrates improved performance over the adaptive elastic net GMM approach in MSE, bias and standard errors. It performs similarly to the AL methods, except in the most high-dimensional cases where AL performs better. However, AL is much more computationally costly than the Sparse group lasso approach. In addition, I apply this method to examine the effects of different Non-Pharmaceutical Interventions (NPIs) on mobility and how mobility influences the transmission of Covid-19. The results reveal that the effectiveness of policy measures varies significantly depending on the demographic characteristics of different areas, highlighting the need for more tailored policy approaches to effectively contain the spread of Covid-19.

